# Generated by Django 4.1.5 on 2023-01-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='contact_number',
        ),
    ]
