# Generated by Django 4.1.5 on 2023-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_babysitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
