# Generated by Django 4.1.5 on 2023-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_babysitter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='time',
            field=models.CharField(choices=[('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM')], default='10 AM', max_length=100),
        ),
    ]
